
name: Daily Build
on:
  schedule:
    - cron: '30 0 * * *'  # 08:30 Beijing (00:30 UTC)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate digest
        env:
          DAILY_SCHEDULE: "00:30 UTC / 08:30 Beijing"
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          python3 scripts/generate_digest.py
          if [ -n "$FEISHU_WEBHOOK" ]; then
            python3 - << 'PY'
import os, json, datetime as dt, urllib.request
date = dt.datetime.utcnow().date().isoformat()
md = f"【数道数金】今日选题推荐 · {date}\n\n"
data = json.load(open(f"docs/data/{date}.json","r",encoding="utf-8"))
for i, r in enumerate(data[:6], 1):
    md += f"{i}. {r.get('idea_title') or r.get('title')}\n   - 来源：{r.get('source','')}\n   - 原文：{r.get('title','')}（{r.get('link','')}）\n   - 标签：{'、'.join(r.get('tags') or [])}\n\n"
payload = json.dumps({"msg_type":"text","content":{"text":md}}, ensure_ascii=False).encode("utf-8")
req = urllib.request.Request(os.environ["FEISHU_WEBHOOK"], data=payload, headers={"Content-Type":"application/json"})
try:
    urllib.request.urlopen(req, timeout=10).read()
except Exception as e:
    print("[warn] feishu push fail:", e)
PY
          fi
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily build" || echo "no changes"
          git push
